### PR TITLE
chore(deps): upgrade to latest

### PR DESCRIPTION
**Pull request by DorMosheZarka**
- ["vite-tsconfig-paths" v5 release notes](https://github.com/aleclarson/vite-tsconfig-paths/releases/tag/v5.0.0)

### CODE REVIEW

**Review by shakederin — APPROVED** [review]
I looked for `isbot` major change and I didn't found anything relevant. 
FYI
https://github.com/codux-templates/website-starter-remix/pull/17

**Comment by idoros** [comment]
@shakederin - can you provide more context?

**Comment by shakederin** [comment]
@idoros is your PR  ready for Merge?

**Comment by idoros** [comment]
merged

**Pull request merged**
